---

teardown: false

required_environment_vars:
    - name: http_proxy
      value: http://localhost:3128/
    - name: https_proxy
      value: http://localhost:3128/
    - name: no_proxy
      value: 127.,172.,10.

docker_environment_vars:
    - name: httpProxy
      value: http://{{ ansible_default_ipv4.address }}:3128/
    - name: httpsProxy
      value: http://{{ ansible_default_ipv4.address }}:3128/
    - name: noProxy
      value: "{{ required_environment_vars[2].value }}"