---

- name: Install required packages
  yum:
      name: "{{ item }}"
  with_items:
      - python-devel
      - openssl-devel

- name: Install pip
  easy_install:
      name: pip

- name: Install ansible
  pip:
      name: ansible
      state: "{{ 'forcereinstall' if desired_ansible_version else 'latest' }}"
      version: "{{ desired_ansible_version }}"